### PR TITLE
Tweaks and suggestions

### PR DESCRIPTION
**Pull request by tig**
Hope you like these tweaks.

I have some more ideas, but this is directionally very good!

### CODE REVIEW

**Comment by tig** [comment]
In https://github.com/gui-cs/Terminal.Gui/pull/3415 I've made significant improvements to Dim.Auto (in order to get Pos.Align to work).

In https://github.com/gui-cs/Terminal.Gui/pull/3376 I've done even more (and have not back-ported to #3415). But I also COMPLETELY refactored AdornmentsEditor. But I'm not done yet and I broke a bunch of unit tests.

For now you may want to rebase this on #3415 so you get the Dim.Auto fixes. With those, you'll be able to have the Scroll correctly resize if you change it's Border which is currently broken in this PR.

**Comment by BDisp** [comment]
Can you rebase it on this PR with the unit tests failures fixes, please? I also have some more fixes to submit but I'll wait until you finish this PR. Thanks.

**Comment by BDisp** [comment]
@tig I'll merge this now to apply immediately your changes, if you don't mind.

**Comment by BDisp** [comment]
I already finished to push my recent changes. If you have some more tweaks please submit more PR. Thanks.

**Pull request merged**
