### PR TITLE
Single multi

### PR DESCRIPTION
**Pull request by tznind**
In order to get us closer to the same page I have added the multi send test from my branch to yours

### CODE REVIEW

**Comment by BDisp** [comment]
Did you realize that we can't even focus the request text field nor the text view. Only the combo box, the send button and the numeric up down button works by mouse. I can't merge this until the navigation issue remain with the tab view.

**Comment by tznind** [comment]
Hmn maybe view needs can focus true

**Comment by BDisp** [comment]
Thanks that fixed the issue. Now in the Multi tab after I set the DAR per second grater than 0 it's always echoing the terminator to the text view.
This variable is never used:
`private DateTime start = DateTime.Now;`

**Comment by BDisp** [comment]
> Thanks that fixed the issue. Now in the Multi tab after I set the DAR per second grater than 0 it's always echoing the terminator to the text view.

Already fixed here https://github.com/gui-cs/Terminal.Gui/pull/3768/commits/64ad1a9901e2dc58041a8e96a114500dc53191ef.

**Comment by BDisp** [comment]
I also fixed an issue where when an iteration is ongoing ensures a new iteration by calling `Application.Invoke`.

**Comment by BDisp** [comment]
Thanks for this.

**Pull request merged**
