### PR TITLE
Add AnsiResponseParser classes

### PR DESCRIPTION
**Pull request by tznind**
This adds just the classes for `AnsiResponseParser<T>`

### CODE REVIEW

**Comment by tznind** [comment]
Ok @BDisp I think this is about as far as I can take it without your help.  I've added my classes and the simplified loop for NetMainLoop [6457bd1](https://github.com/BDisp/Terminal.Gui/pull/202/commits/6457bd114fac92a98a1f094e84f67c255ed59b57).  This works.

I tried to add my changes to Net events in [79e52d4](https://github.com/BDisp/Terminal.Gui/pull/202/commits/79e52d4f1d4f5e14362b2838a7b6cc417517ff7e) but when I send an ansi request it hangs up (also Esc alone does not get handled).

Can you please look at what I did in 79e52d4 and try to implement similar pattern.  I've not added the scheduler/parser tests but if you like I can add them to this PR.


Next steps
=============
The `AnsiResponseParser<ConsoleKeyInfo>` replaces most of the existing code in NetEvents.  It filters the incoming keys and extracts and raises events.  It needs the main iteration of the input processing to periodically call Release depending on parser state (again see my diff).

Let me know if you have questions.

If we focus solely on `NetDriver` then the other two should just fall into place as NetDriver is the hardest and most complicated currently - at least before my changes to simplify it ;).

**Comment by BDisp** [comment]
Frankly, I think it's too exaggerated to send too many requests at once. I think it's preferable to send whenever the user needs it. It's one thing to send escape sequences to modify colors when writing that you're just sending to the output and not waiting for a response back, in which case we can send those escape sequences at will. Now in requests, the user submits the requests and expects it back as soon as possible. So it looks like a denial of service (DOS) attack.

**Comment by tznind** [comment]
I agree it is overkill scenario, I wrote it that way deliberately to stress test the solution. 

We want our approach to be as maintainable and robust as possible.

**Comment by BDisp** [comment]
I already improved WindowsDriver to respond better while we're typing with 5 requests but with 20 it's a chaos. I'll also improve the others drivers.

**Comment by tznind** [comment]
That's great.  Knowing the limits is what it's all about!

 And handling common cases, this is why I added throttling to ansi scheduler.

**Pull request closed without merging**
