### PR TITLE
Updated FramesEditor layout, fixed ColorPicker, fixed RadioGroup

### PR DESCRIPTION
**Pull request by tig**
Got motivated to work on this on the plane. I hope you like it!

### CODE REVIEW

**Comment by tig** [comment]
@BDisp did you see this PR to your PR?

**Comment by BDisp** [comment]
> @BDisp did you see this PR to your PR?

I didn't saw before, sorry. Please resolve the conflicts.

**Comment by tig** [comment]
Done

**Comment by BDisp** [comment]
That a great improvement. Thanks.

**Pull request merged**
