### PR TITLE
Fixes merge issues?

### PR DESCRIPTION
**Pull request by tig**
I think.

### CODE REVIEW

**Comment by tig** [comment]
Trying to fix this all now.

**Comment by tig** [comment]
@BDisp Please carefully check that I didn't undo any of your fixes that matter. I think this finally brings all of this together.

**Comment by BDisp** [comment]
@tig this is equal to mine after merge and really some of fixes was undo. I already fix all merge errors. I can run it but some unit tests are failing. I'll push my changes to my PR to you also check, please.

**Comment by tig** [comment]
> @tig this is equal to mine after merge and really some of fixes was undo. I already fix all merge errors. I can run it but some unit tests are failing. I'll push my changes to my PR to you also check, please.

It's not completely equal because all unit test pass. However, in https://github.com/gui-cs/Terminal.Gui/pull/2385, unit tests are failing.

**Comment by tig** [comment]
Note, I was very careful to do each change as a separate commit, so hopefully that will help figure out what I actually fixed vs. just duplicated.

**Pull request merged**
