### PR TITLE
Prototype/WIP for revamping how cursor handling works

### PR DESCRIPTION
**Pull request by tig**
I started with just doing a code-review of @BDisp's PR but quickly realized that his proposed solution didn't fix all cases and caused other problems. 

As i do in cases like this, I run a bunch of experiments to make sure I understand the bigger picture and then I try to articulate requirements. 

I ran out of time and so this PR to @BDisp's PR is NOTHING MORE THAN A WIP PROTOTYPE, but I did learn enough to gain clarity on some requirements for how cursor handling in Terminal.Gui SHOULD work:

- By default, a View or View sub-class should not show the cursor, and should not have to do anything (this is already the case).
- Views that just want to show the cursor at a particular location in the Viewport should only have to:
  - Declare the style of cursor they want (e.g. "DesiredCursorVisibiltiy" or equivalent should be a property on `View`).
  - Tell the system the location (debatable if this should be in content or viewport-relative coords).
- View sub-class code should NEVER call a `Driver.` API
- Application should take care of ensuring the cursor is visible or not, calling into Driver
- It should be possible for Views to do complex things (although I struggle the conceive of anything more advanced than, say, what 'Editor' or `CharMap` do, which is actually very simple.

### CODE REVIEW

**Comment by BDisp** [comment]
@tig, that really a great work but still has an issue. Test with the Content Scrolling scenario by scrolling to the left or to the right, either on the TextField or the TextView. When the scrolling direction is inverted the cursor doesn't show anymore.

**Comment by tig** [comment]
While it's on my mind, here are some of the issues I have with the current cursor design;

## `Driver.Row/Pos`, which are changed via `Move` serves two purposes that confuse each other:

a) Where the next `AddRune` will put the next rune
b) The current "Cursor Location"

If most TUI apps acted like a command line where the visible cursor was always visible, this might make sense. But the fact that only a very few View subclasses we've seen actually care to show the cursor illustrates a problem:

Any drawing causes the "Cursor Position" to be changed/lost. This means we have a ton of code that is constantly repositioning the cursor every MainLoop iteration.

## The actual cursor position RARELY changes (relative to `Mainloop.Iteration`).

Derived from abo`ve, the current design means we need to call `View.PositionCursor` every iteration. For some views this is a low-cost operation. For others it involves a lot of math. 

This is just stupid. 

## Flicker

Related to the above, we need constantly Show/Hide the cursor every iteration. This causes ridiculous cursor flicker.

**Comment by tig** [comment]
## `View.PositionCursor` is poorly spec'd and confusing to implement correctly

Should a view call `base.PositionCursor`? If so, before or after doing stuff? 

## Setting cursor visibility in `OnEnter` actually makes no sense

First, leaving it up to views to do this is fragile.

Second, when a View gets focus is but one of many places where cursor visibilty should be updated.

**Comment by BDisp** [comment]
@tig I decided merge your great PR, thanks. I fixed the issues I'd mentioned and the failed unit tests. Feel free for submit more PR. You solution by let the Application handle the cursor was a very good idea.

**Comment by tig** [comment]
Nice! Thanks. 

I'd really appreciate you reading cursor.md carefully and providing your thoughts and questions.

**Pull request merged**
